<?php

return [
    'actions' => [
        'view' => 'Lihat',
        'create' => 'Tambah',
        'update' => 'Ubah',
        'delete' => 'Hapus',
    ],

    'features' => [
        'users' => [
            'label' => 'Kelola User',
            'patterns' => ['admin.users.*'],
            'paths' => ['admin/users*'],
        ],
        'chat' => [
            'label' => 'Live Chat',
            'patterns' => ['admin.chat.*'],
            'paths' => ['admin/chat*'],
        ],
        'reviews' => [
            'label' => 'Ulasan Produk',
            'patterns' => ['admin.reviews.*'],
            'paths' => ['admin/reviews*'],
        ],
        'hotel_properties' => [
            'label' => 'Hotel - Properti',
            'parent' => 'Hotel',
            'patterns' => ['hotels.*'],
            'paths' => ['hotels*'],
        ],
        'hotel_rooms' => [
            'label' => 'Hotel - Kamar & Inventory',
            'parent' => 'Hotel',
            'patterns' => ['room-types.*', 'room-inventories.*'],
            'paths' => ['room-types*', 'room-inventories*'],
        ],
        'hotel_bookings' => [
            'label' => 'Hotel - Booking',
            'parent' => 'Hotel',
            'patterns' => ['admin.bookings.*', 'admin.hotel.exceptions.*'],
            'paths' => ['admin/bookings*', 'admin/hotel/exceptions*'],
        ],
        'hotel_finance' => [
            'label' => 'Hotel - Keuangan & Payout',
            'parent' => 'Hotel',
            'patterns' => ['admin.finance.*', 'admin.payouts.*'],
            'paths' => ['admin/finance*'],
        ],
        'hotel_vouchers' => [
            'label' => 'Hotel - Voucher',
            'parent' => 'Hotel',
            'patterns' => ['admin.vouchers.*'],
            'paths' => ['admin/marketing/vouchers*'],
        ],
        'mitra' => [
            'label' => 'Kelola Mitra - Hotel',
            'parent' => 'Kelola Mitra',
            'patterns' => ['admin.mitra.*'],
            'paths' => ['admin/mitra*'],
        ],
        'mitra_wisata' => [
            'label' => 'Kelola Mitra - Wisata',
            'parent' => 'Kelola Mitra',
            'patterns' => ['admin.mitra-wisata.*'],
            'paths' => ['admin/mitra-wisata*'],
        ],
        'mitra_events' => [
            'label' => 'Kelola Mitra - Event',
            'parent' => 'Kelola Mitra',
            'patterns' => ['admin.events.organizers.*'],
            'paths' => ['admin/events/organizers*'],
        ],
        'mitra_documents' => [
            'label' => 'Kelola Mitra - Dokumen S&K',
            'parent' => 'Kelola Mitra',
            'patterns' => ['admin.mitra-documents.*'],
            'paths' => ['admin/mitra-documents*'],
        ],
        'mitra_all' => [
            'label' => 'Kelola Mitra - Semua Mitra',
            'parent' => 'Kelola Mitra',
            'patterns' => ['admin.mitra.*', 'admin.mitra-wisata.*', 'admin.events.organizers.*', 'admin.mitra-documents.*'],
            'paths' => ['admin/mitra*', 'admin/mitra-wisata*', 'admin/events/organizers*', 'admin/mitra-documents*'],
        ],
        'wisata_destinations' => [
            'label' => 'Wisata - Destinasi',
            'parent' => 'Wisata',
            'patterns' => ['admin.wisata.destinations.*'],
            'paths' => ['admin/wisata/destinations*'],
        ],
        'wisata_tickets' => [
            'label' => 'Wisata - Tiket',
            'parent' => 'Wisata',
            'patterns' => ['admin.wisata.tickets.*'],
            'paths' => ['admin/wisata/tickets*'],
        ],
        'wisata_bookings' => [
            'label' => 'Wisata - Booking & Scan',
            'parent' => 'Wisata',
            'patterns' => ['admin.wisata.bookings.*', 'admin.wisata.scans.*'],
            'paths' => ['admin/wisata/bookings*', 'admin/wisata/scans*'],
        ],
        'wisata_finance' => [
            'label' => 'Wisata - Keuangan',
            'parent' => 'Wisata',
            'patterns' => ['admin.wisata.finance.*'],
            'paths' => ['admin/wisata/finance*'],
        ],
        'wisata_content' => [
            'label' => 'Wisata - Konten & Operasional',
            'parent' => 'Wisata',
            'patterns' => ['admin.wisata.content.*', 'admin.wisata.exceptions.*'],
            'paths' => ['admin/wisata/content*', 'admin/wisata/exceptions*'],
        ],
        'wisata_affiliates' => [
            'label' => 'Afiliasi Wisata',
            'patterns' => ['admin.wisata.affiliates.*'],
            'paths' => ['admin/wisata/affiliates*'],
        ],
        'events_items' => [
            'label' => 'Event - Event',
            'parent' => 'Event',
            'patterns' => ['admin.events.index', 'admin.events.show', 'admin.events.store', 'admin.events.update', 'admin.events.destroy'],
            'paths' => ['admin/events', 'admin/events/*'],
        ],
        'events_tickets' => [
            'label' => 'Event - Tiket',
            'parent' => 'Event',
            'patterns' => ['admin.events.tickets.*'],
            'paths' => ['admin/events/tickets*'],
        ],
        'events_bookings' => [
            'label' => 'Event - Booking & Peserta',
            'parent' => 'Event',
            'patterns' => ['admin.events.bookings.*', 'admin.events.attendees.*', 'admin.events.scans.*'],
            'paths' => ['admin/events/bookings*', 'admin/events/attendees*', 'admin/events/scans*'],
        ],
        'events_finance' => [
            'label' => 'Event - Keuangan',
            'parent' => 'Event',
            'patterns' => ['admin.events.finance.*'],
            'paths' => ['admin/events/finance*'],
        ],
        'events_content' => [
            'label' => 'Event - Konten & Review',
            'parent' => 'Event',
            'patterns' => ['admin.events.content.*', 'admin.events.reviews.*', 'admin.events.exceptions.*'],
            'paths' => ['admin/events/content*', 'admin/events/reviews*', 'admin/events/exceptions*'],
        ],
        'events_system' => [
            'label' => 'Event - Audit & Pengaturan',
            'parent' => 'Event',
            'patterns' => ['admin.events.system.*'],
            'paths' => ['admin/events/system*'],
        ],
        'academy_classes' => [
            'label' => 'Academy - Kelas',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.classes.*'],
            'paths' => ['admin/academy/classes*'],
        ],
        'academy_tickets' => [
            'label' => 'Academy - Tiket',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.tickets.*'],
            'paths' => ['admin/academy/tickets*'],
        ],
        'academy_bookings' => [
            'label' => 'Academy - Booking & Peserta',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.bookings.*', 'admin.academy.attendees.*'],
            'paths' => ['admin/academy/bookings*', 'admin/academy/attendees*'],
        ],
        'academy_scans' => [
            'label' => 'Academy - Scan QR',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.scans.*'],
            'paths' => ['admin/academy/scans*'],
        ],
        'academy_finance' => [
            'label' => 'Academy - Keuangan & Laporan',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.finance.*', 'admin.academy.reports.*'],
            'paths' => ['admin/academy/finance*', 'admin/academy/reports*'],
        ],
        'academy_system' => [
            'label' => 'Academy - Audit & Pengaturan',
            'parent' => 'Eljohn Academy',
            'patterns' => ['admin.academy.audit.*', 'admin.academy.settings.*'],
            'paths' => ['admin/academy/system*'],
        ],
        'retail_products' => [
            'label' => 'Retail Shop - Produk',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.products.*'],
            'paths' => ['admin/retail-shop/products*'],
        ],
        'retail_categories' => [
            'label' => 'Retail Shop - Kategori',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.categories.*'],
            'paths' => ['admin/retail-shop/categories*'],
        ],
        'retail_variants' => [
            'label' => 'Retail Shop - Variasi Produk',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.variants.*'],
            'paths' => ['admin/retail-shop/variants*'],
        ],
        'retail_inventory' => [
            'label' => 'Retail Shop - Inventory & Stok',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.inventory.*'],
            'paths' => ['admin/retail-shop/inventory*'],
        ],
        'retail_orders' => [
            'label' => 'Retail Shop - Order & Fulfillment',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.orders.*', 'admin.souvenir.fulfillment.*'],
            'paths' => ['admin/retail-shop/orders*', 'admin/retail-shop/fulfillment*'],
        ],
        'retail_refunds' => [
            'label' => 'Retail Shop - Refund & Retur',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.refunds.*'],
            'paths' => ['admin/retail-shop/refunds*'],
        ],
        'retail_promotions' => [
            'label' => 'Retail Shop - Promo',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.promotions.*'],
            'paths' => ['admin/retail-shop/promotions*'],
        ],
        'retail_reports' => [
            'label' => 'Retail Shop - Laporan',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.reports.*'],
            'paths' => ['admin/retail-shop/reports*'],
        ],
        'retail_system' => [
            'label' => 'Retail Shop - Audit & Pengaturan',
            'parent' => 'Retail Shop',
            'patterns' => ['admin.souvenir.audit.*', 'admin.souvenir.settings.*'],
            'paths' => ['admin/retail-shop/audit*', 'admin/retail-shop/settings*'],
        ],
        'special_programs' => [
            'label' => 'Special Program - Program',
            'parent' => 'Special Program',
            'patterns' => ['admin.special-programs.index', 'admin.special-programs.create', 'admin.special-programs.store', 'admin.special-programs.show', 'admin.special-programs.edit', 'admin.special-programs.update', 'admin.special-programs.destroy', 'admin.special-programs.status'],
            'paths' => ['admin/special-programs', 'admin/special-programs/create', 'admin/special-programs/*/edit'],
        ],
        'special_program_tickets' => [
            'label' => 'Special Program - Tiket',
            'parent' => 'Special Program',
            'patterns' => ['admin.special-programs.tickets.*'],
            'paths' => ['admin/special-programs/tickets*'],
        ],
        'special_program_bookings' => [
            'label' => 'Special Program - Booking & Peserta',
            'parent' => 'Special Program',
            'patterns' => ['admin.special-programs.bookings.*', 'admin.special-programs.attendees.*'],
            'paths' => ['admin/special-programs/bookings*', 'admin/special-programs/attendees*'],
        ],
        'special_program_scans' => [
            'label' => 'Special Program - Scan QR',
            'parent' => 'Special Program',
            'patterns' => ['admin.special-programs.scans.*'],
            'paths' => ['admin/special-programs/scans*'],
        ],
        'special_program_reviews' => [
            'label' => 'Special Program - Review',
            'parent' => 'Special Program',
            'patterns' => ['admin.special-programs.reviews.*'],
            'paths' => ['admin/special-programs/reviews*'],
        ],
        'blog_posts' => [
            'label' => 'Jelajah Indotix - Artikel',
            'parent' => 'Jelajah Indotix',
            'patterns' => ['admin.blog.posts.*'],
            'paths' => ['admin/blog/posts*'],
        ],
        'blog_categories' => [
            'label' => 'Jelajah Indotix - Kategori',
            'parent' => 'Jelajah Indotix',
            'patterns' => ['admin.blog.categories.*'],
            'paths' => ['admin/blog/categories*'],
        ],
        'blog_tags' => [
            'label' => 'Jelajah Indotix - Tags',
            'parent' => 'Jelajah Indotix',
            'patterns' => ['admin.blog.tags.*'],
            'paths' => ['admin/blog/tags*'],
        ],
        'public_home' => [
            'label' => 'Konten Publik - Halaman Home',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.home.*'],
            'paths' => ['admin/public/home*'],
        ],
        'public_banners' => [
            'label' => 'Konten Publik - Banner',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.banners.*'],
            'paths' => ['admin/public/banners*'],
        ],
        'public_promo_items' => [
            'label' => 'Konten Publik - Promo Spesial',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.promo-items.*'],
            'paths' => ['admin/public/promo-items*'],
        ],
        'public_contacts' => [
            'label' => 'Konten Publik - Kontak & WhatsApp',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.contacts.*'],
            'paths' => ['admin/public/contacts*'],
        ],
        'public_partners' => [
            'label' => 'Konten Publik - Partner Kami',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.partners.*'],
            'paths' => ['admin/public/partners*'],
        ],
        'public_pages' => [
            'label' => 'Konten Publik - Halaman & Dokumen Legal',
            'parent' => 'Konten Publik',
            'patterns' => ['admin.public.about.*', 'admin.public.faqs.*', 'admin.public.privacy-policy.*'],
            'paths' => ['admin/public/about*', 'admin/public/faqs*', 'admin/public/privacy-policy*'],
        ],
        'system_audit' => [
            'label' => 'Sistem - Audit Log',
            'parent' => 'Sistem, Audit & Kontrol',
            'patterns' => ['admin.audit-logs.*'],
            'paths' => ['admin/system/audit-logs*'],
        ],
        'system_settings' => [
            'label' => 'Sistem - Pengaturan & Reset',
            'parent' => 'Sistem, Audit & Kontrol',
            'patterns' => ['admin.system.settings.*', 'admin.system.reset'],
            'paths' => ['admin/system/settings*', 'admin/system/reset*'],
        ],
        'system_notifications' => [
            'label' => 'Sistem - Notifikasi',
            'parent' => 'Sistem, Audit & Kontrol',
            'patterns' => ['admin.system.notifications.*'],
            'paths' => ['admin/system/notifications*'],
        ],
        'system_roles' => [
            'label' => 'Sistem - Role & RBAC',
            'parent' => 'Sistem, Audit & Kontrol',
            'patterns' => ['admin.system.roles.*'],
            'paths' => ['admin/system/roles*'],
        ],
        'system_special_admins' => [
            'label' => 'Sistem - Admin Khusus',
            'parent' => 'Sistem, Audit & Kontrol',
            'patterns' => ['admin.system.special-admins.*'],
            'paths' => ['admin/system/special-admins*'],
        ],
    ],
];
