import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import { Button } from '@/components/ui/button';
import type { BreadcrumbItem } from '@/types';

const breadcrumbs: BreadcrumbItem[] = [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Mobile App', href: '/admin/mobile/home' }, { title: 'Hero Media', href: '/admin/mobile/home' }];
export default function MobileHeroesIndex({ heroes }: { heroes: Array<Record<string, any>> }) {
    return <AppLayout breadcrumbs={breadcrumbs}><Head title="Mobile Hero Media" /><main className="flex flex-1 flex-col gap-6 p-6"><header className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold">Mobile App Home Content</h1><p className="mt-1 text-sm text-muted-foreground">Hero Media hanya digunakan oleh aplikasi Mobile Indotix dan tidak memengaruhi Website.</p></div><Button asChild><Link href="/admin/mobile/home/heroes/create">Tambah Hero</Link></Button></header><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Preview</th><th className="p-4">Konten</th><th className="p-4">Media</th><th className="p-4">Status</th><th className="p-4">Urutan</th><th className="p-4">Aksi</th></tr></thead><tbody>{heroes.map(hero => <tr className="border-b" key={hero.id}><td className="p-4">{hero.media_type === 'video' ? <video src={hero.media_url} poster={hero.poster_url ?? undefined} muted className="h-20 w-32 rounded object-cover" /> : <img src={hero.media_url ?? hero.poster_url} alt={hero.title} className="h-20 w-32 rounded object-cover" />}</td><td className="p-4"><div className="font-medium">{hero.title}</div><div className="text-xs text-muted-foreground">{hero.highlight_title}</div></td><td className="p-4 uppercase">{hero.media_type}</td><td className="p-4">{hero.is_active ? 'Aktif' : 'Nonaktif'}</td><td className="p-4">{hero.sort_order}</td><td className="p-4"><Link className="text-primary" href={`/admin/mobile/home/heroes/${hero.id}/edit`}>Edit</Link><button className="ml-4 text-destructive" onClick={() => { if (window.confirm('Hapus Hero Mobile ini?')) router.delete(`/admin/mobile/home/heroes/${hero.id}`); }}>Hapus</button></td></tr>)}</tbody></table></div></main></AppLayout>;
}
