import { Head, useForm } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import InputError from '@/components/input-error';
import type { BreadcrumbItem } from '@/types';
const breadcrumbs: BreadcrumbItem[] = [{ title: 'Dashboard', href: '/dashboard' }, { title: 'Mobile App', href: '/admin/mobile/promos' }, { title: 'Tambah Promo', href: '/admin/mobile/promos/create' }];
export default function MobilePromoCreate() { const form = useForm({ name: '', alt_text: '', target_url: '', sort_order: 0, starts_at: '', ends_at: '', is_active: true, image: null as File | null }); return <AppLayout breadcrumbs={breadcrumbs}><Head title="Tambah Mobile Promo" /><main className="p-6"><form className="grid max-w-2xl gap-4 rounded-xl border bg-card p-6" onSubmit={e => { e.preventDefault(); form.post('/admin/mobile/promos', { forceFormData: true }); }}><h1 className="text-2xl font-semibold">Tambah Mobile Promo</h1><p className="text-sm text-muted-foreground">Asset ini hanya digunakan oleh aplikasi Mobile Indotix. Rekomendasi 1200 x 530 px, rasio sekitar 2.26:1.</p><Field label="Nama internal" value={form.data.name} error={form.errors.name} onChange={v => form.setData('name', v)} /><Field label="Alt text" value={form.data.alt_text} error={form.errors.alt_text} onChange={v => form.setData('alt_text', v)} /><Field label="Target URL" value={form.data.target_url} error={form.errors.target_url} onChange={v => form.setData('target_url', v)} /><Field label="Urutan" type="number" value={String(form.data.sort_order)} error={form.errors.sort_order} onChange={v => form.setData('sort_order', Number(v))} /><div className="grid grid-cols-2 gap-3"><Field label="Mulai" type="datetime-local" value={form.data.starts_at} error={form.errors.starts_at} onChange={v => form.setData('starts_at', v)} /><Field label="Selesai" type="datetime-local" value={form.data.ends_at} error={form.errors.ends_at} onChange={v => form.setData('ends_at', v)} /></div><Input type="file" required accept="image/jpeg,image/png,image/webp" onChange={e => form.setData('image', e.target.files?.[0] ?? null)} /><InputError message={form.errors.image} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.data.is_active} onChange={e => form.setData('is_active', e.target.checked)} /> Aktif</label><Button type="submit">Simpan</Button></form></main></AppLayout>; }
function Field({ label, value, error, onChange, type = 'text' }: { label: string; value: string; error?: string; onChange: (value: string) => void; type?: string }) { return <div className="grid gap-2"><Label>{label}</Label><Input type={type} value={value} onChange={e => onChange(e.target.value)} /><InputError message={error} /></div>; }
